### ISSUE TITLE
Server Side Javascript

### ISSUE THREAD

**Issue by ghost** [webpop/extensions#1]
Isn't it a little dangerous running untrusted end user code on the server? How do you know the end user won't do something evil like delete a bunch of files, trash the database or cause endless loops?

I'd be interested to know how you handle this and if it is safe.

**Comment by biilmann** [comment]
Hi Jamie,

Pretty much each time you visit a website you end up running untrusted
javascript that your browser just downloaded. Fortunately javascript is
designed with this in mind and there's no standard library you can load
from javascript that will let you do malicious stuff to a users files or
the like.

We picked javascript for our extension engine for this reason. There's no
big standard library that we would have to lock down. Instead we
can carefully pick methods that we expose to the javascript extension
engine that will let it interact with our database and the files stored in
our distributed file system in a safe and controlled way.

In our current implementation we use Rhino, a javascript engine implemented
in Java. This lets us do extra check such as limiting the execution time or
the instruction count used by a javascript extension. An endless loop will
simply get killed by our extension engine.

Hope that clears it up.

Cheers,
Mathias

**Comment by ghost** [comment]
That clears things up, thanks.

That's quite an interesting implementation, are you actually using commonjs or just an API similar to commonjs i.e. just custom `require` and `exports` globals?

I have a similar need for something like this but using therubyracer gem, it doesn't have support for commonjs however, hence my question.

**Comment by biilmann** [comment]
We're using our own implementation of the CommonJS module system, since we
need to make sure that require and file operations always operate in the
context of the project the extension is part of. So our implementation is
quite specific to our needs.

Cheers,
Mathias
